---
image:
  name: 583812563872.dkr.ecr.ap-southeast-2.amazonaws.com/linux-packer:latest
  aws:
      access-key: $AWS_ACCESS_KEY_ID
      secret-key: $AWS_SECRET_ACCESS_KEY
pipelines:
  default:
    -
      step:
        script:
         - make deps
         - aws sts get-caller-identity
         - make build-docker-base
         - make publish-docker-base
