---
image:
  name: 583812563872.dkr.ecr.ap-southeast-2.amazonaws.com/linux-packer:latest
  aws:
      access-key: $AWS_ACCESS_KEY_ID
      secret-key: $AWS_SECRET_ACCESS_KEY
pipelines:
  default:
    -
      step:
        script:
         - mkdir ~/.
         - touch ~/.aws/credentials
         - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
         - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
         - make deps
         - aws sts get-caller-identity
         - make deps
         - make build-docker-base
         - make publish-docker-base
