---
image:
  name: 583812563872.dkr.ecr.ap-southeast-2.amazonaws.com/packer:latest
  aws:
      access-key: $AWS_ACCESS_KEY_ID
      secret-key: $AWS_SECRET_ACCESS_KEY
pipelines:
  default:
    -
      step:
        script:
         - python3 -m ensurepip --upgrade
         - make deps
         - aws sts get-caller-identity
