clone:
  depth: full
image: python:3.7.2
pipelines:
  branches:
    main:
      - step:
         script:
           - python3 -m ensurepip --upgrade
           - make deps
           - aws sts get-caller-identity
