---

- name: Publish the Docker image to repository
  hosts: all
  gather_facts: false
  connection: local

  tasks:

    - name: Tagging the docker image
      ansible.builtin.shell: 'docker tag {{ docker.repository.base }}/{{ docker.image.name }}:latest 583812563872.dkr.ecr.ap-southeast-2.amazonaws.com/{{ docker.repository.base }}:{{docker.image.name}}'

    - name: Publish the Docker image with latest tag
      ansible.builtin.shell: "docker push 583812563872.dkr.ecr.ap-southeast-2.amazonaws.com/{{ docker.repository.base }}:{{ docker.image.name }}"
